services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dhdv_sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - TZ=Asia/Bangkok
    ports: ["1433:1433"]
    volumes:
      - mssql_data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
    networks: [appnet]
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dhdv_web
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=dhdv_sql,1433;Database=dhdv;User ID=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True
      - TZ=Asia/Bangkok
    ports: ["8080:8080"]
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
    depends_on: [sql]
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:8080/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [appnet]
    restart: unless-stopped

  cf:
    image: cloudflare/cloudflared:latest
    container_name: dhdv_cf
    command: ["tunnel","--no-autoupdate","run","--token","${TUNNEL_TOKEN}"]
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TZ=Asia/Bangkok
    depends_on: [web]
    networks: [appnet]
    restart: unless-stopped

networks: { appnet: {} }
volumes:   { mssql_data: {} }
